"""Signed session cookies — the identity the memory endpoints trust.

Before this, `user_id` arrived as a query parameter or JSON field generated by the browser
with `Math.random()`. Anyone who knew or guessed another person's id could read, edit,
delete or export their entire memory and conversation history:

    GET /memory?user_id=satsang_user-2jxex40r  ->  200 OK  {...their facts...}

That is personal data, and §7 promises the person controls it. Control means nobody else
has it. So identity now comes from an HMAC-signed, HttpOnly cookie the server issues: the
client can present it but cannot forge or enumerate one, and JavaScript cannot read it.

Deliberately minimal — no accounts, no passwords, no email. The product needs *continuity*
and *isolation*, not authentication. Someone who clears their cookies is simply a new
person, which is the honest behaviour for a companion nobody has signed up to.
"""
from __future__ import annotations

import hashlib
import hmac
import os
import secrets
from pathlib import Path

from fastapi import Request, Response

COOKIE = "satsang_session"
_MAX_AGE = 60 * 60 * 24 * 365            # a year; conversations span months
_SECRET_FILE = Path(__file__).resolve().parent / "data" / ".session_secret"


def _secret() -> bytes:
    """HMAC key: env first (set it in production so restarts don't invalidate sessions),
    otherwise a persisted random file. Never a hard-coded default — a shipped constant
    would let anyone forge a cookie for any user."""
    env = os.environ.get("SATSANG_SECRET_KEY")
    if env:
        return env.encode()
    if _SECRET_FILE.exists():
        return _SECRET_FILE.read_bytes()
    key = secrets.token_bytes(32)
    _SECRET_FILE.parent.mkdir(parents=True, exist_ok=True)
    _SECRET_FILE.write_bytes(key)
    try:
        _SECRET_FILE.chmod(0o600)
    except OSError:
        pass
    return key


def _sign(uid: str) -> str:
    mac = hmac.new(_secret(), uid.encode(), hashlib.sha256).hexdigest()[:32]
    return f"{uid}.{mac}"


def _verify(token: str) -> str | None:
    uid, _, mac = (token or "").rpartition(".")
    if not uid or not mac:
        return None
    expected = hmac.new(_secret(), uid.encode(), hashlib.sha256).hexdigest()[:32]
    # compare_digest, not ==, so a timing side-channel cannot leak the signature
    return uid if hmac.compare_digest(mac, expected) else None


def new_user_id() -> str:
    """token_urlsafe, not Math.random: ids must not be guessable or enumerable."""
    return "u_" + secrets.token_urlsafe(16)


def current_user(request: Request, response: Response) -> str:
    """The caller's id, from their signed cookie. Mints one on first visit.

    Every memory endpoint depends on THIS and ignores any client-supplied user_id, so a
    request can only ever touch its own data.
    """
    uid = _verify(request.cookies.get(COOKIE, ""))
    if uid is None:
        uid = new_user_id()
        response.set_cookie(
            COOKIE, _sign(uid), max_age=_MAX_AGE,
            httponly=True,          # JS cannot read it -> XSS cannot steal the session
            samesite="lax",         # not sent on cross-site POSTs -> basic CSRF cover
            secure=request.url.scheme == "https",
            path="/")
    return uid
